# Makefile--
# AUTHOR:Ruikang Dai
# DATE:Tue Jan 27 21:31:31 EST 2015
function-pointer: function-pointer.o
	cc function-pointer.o -o function-pointer
function-pointer.o: function-pointer.c
	cc -c function-pointer.c