# Makefile--
# AUTHOR:Ruikang Dai
# DATE:Thu Apr 16 07:31:36 EDT 2015
sigactionExample: sigactionExample.o
	cc sigactionExample.o -o sigactionExample
sigactionExample.o: sigactionExample.c
	cc -c sigactionExample.c