# Makefile--
# AUTHOR:Ruikang Dai
# DATE:Sat Feb  7 11:41:24 EST 2015
opEx6: opEx6.o
	cc opEx6.o -o opEx6
opEx6.o: opEx6.c
	cc -c opEx6.copEx6: opEx6.o
	cc opEx6.o -o opEx6
opEx6.o: opEx6.c
	cc -c opEx6.c