# Makefile--
# AUTHOR:Ruikang Dai
# DATE:Tue Feb 10 20:54:15 EST 2015
DynamicMemoryAllocation: DynamicMemoryAllocation.o
	cc DynamicMemoryAllocation.o -o DynamicMemoryAllocation
DynamicMemoryAllocation.o: DynamicMemoryAllocation.c
	cc -c DynamicMemoryAllocation.c