# Makefile--
# AUTHOR:Ruikang Dai
# DATE:Mon Mar 16 09:24:50 EDT 2015
catchINTsignal3times: catchINTsignal3times.o
	cc catchINTsignal3times.o -o catchINTsignal3times
catchINTsignal3times.o: catchINTsignal3times.c
	cc -c catchINTsignal3times.c