# Makefile--Directly type make the program will be compiled with unix clang complier
# AUTHOR:Ruikang Dai
# DATE:Sun Jan 25 18:15:37 EST 2015
Homework_1: Homework_1.o
	cc Homework_1.o -o Homework_1
Homework_1.o: Homework_1.c
	cc -c Homework_1.c
