# Makefile--
# AUTHOR:Ruikang Dai
# DATE:Wed Feb 11 12:33:27 EST 2015
preCompileTest: preCompileTest.o
	cc preCompileTest.o -o preCompileTest
preCompileTest.o: preCompileTest.c
	cc -c preCompileTest.c