# Makefile--
# AUTHOR:Ruikang Dai
# DATE:Wed Feb  4 17:12:00 EST 2015
OverviewPart3Ex1: OverviewPart3Ex1.o
	cc OverviewPart3Ex1.o -o OverviewPart3Ex1
OverviewPart3Ex1.o: OverviewPart3Ex1.c
	cc -c OverviewPart3Ex1.c